### PR TITLE
fix(nextjs): Call next navigate even when instantly resolving the awaitableNavigate

### PR DESCRIPTION
**Pull request by desiprisg**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

In this hook, we instantly resolve the promise since we won't be able to detect that `router.push` has finished executing. However, we have forgotten to actually run `router.push`, in order to trigger any side effects that `router.push` triggers. One example is having to call `router.push` on the url we are on, in order for middleware to re-execute and redirect us when the auth state changes (for app router).

### CODE REVIEW

**Comment by SokratisVidros** [comment]
@desiprisg can you please elaborate on what issue does this solve?

**Comment by desiprisg** [comment]
@SokratisVidros  Updated the description

**Review by nikosdouvlis — APPROVED** [review]
This makes sense to me

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
