### PR TITLE
fix(nextjs,shared): Revert "Use `use client` directive to support sha…

### PR DESCRIPTION
**Pull request by nikosdouvlis**
Temporarily resolve
```
 ⨯ node_modules/@clerk/shared/dist/cjs/hooks/createContextAndHook.js (43:35) @ createContext
 ⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at createContextAndHook (webpack-internal:///(rsc)/./node_modules/@clerk/shared/dist/cjs/hooks/createContextAndHook.js:48:38)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/shared/dist/cjs/hooks/contexts.js:53:110)
```

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.4.4-snapshot.e37df91 |
| @clerk/clerk-js | 4.59.1-snapshot.e37df91 |
| @clerk/clerk-expo | 0.19.6-snapshot.e37df91 |
| gatsby-plugin-clerk | 4.4.12-snapshot.e37df91 |
| @clerk/nextjs | 4.25.1-snapshot.e37df91 |
| @clerk/clerk-react | 4.26.1-snapshot.e37df91 |
| @clerk/remix | 3.0.3-snapshot.e37df91 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.4.4-snapshot.e37df91
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.59.1-snapshot.e37df91
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.19.6-snapshot.e37df91
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.12-snapshot.e37df91
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.25.1-snapshot.e37df91
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.26.1-snapshot.e37df91
```
```sh
# @clerk/remix
npm i @clerk/remix@3.0.3-snapshot.e37df91
```

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.4.4-snapshot.aae1150 |
| @clerk/clerk-js | 4.59.1-snapshot.aae1150 |
| @clerk/clerk-expo | 0.19.6-snapshot.aae1150 |
| gatsby-plugin-clerk | 4.4.12-snapshot.aae1150 |
| @clerk/nextjs | 4.25.1-snapshot.aae1150 |
| @clerk/clerk-react | 4.26.1-snapshot.aae1150 |
| @clerk/remix | 3.0.3-snapshot.aae1150 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.4.4-snapshot.aae1150
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.59.1-snapshot.aae1150
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.19.6-snapshot.aae1150
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.12-snapshot.aae1150
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.25.1-snapshot.aae1150
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.26.1-snapshot.aae1150
```
```sh
# @clerk/remix
npm i @clerk/remix@3.0.3-snapshot.aae1150
```

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.30.1-snapshot.cecf74d |
| @clerk/chrome-extension | 0.4.4-snapshot.cecf74d |
| @clerk/clerk-js | 4.59.1-snapshot.cecf74d |
| @clerk/clerk-expo | 0.19.6-snapshot.cecf74d |
| @clerk/fastify | 0.6.11-snapshot.cecf74d |
| gatsby-plugin-clerk | 4.4.12-snapshot.cecf74d |
| @clerk/nextjs | 4.25.1-snapshot.cecf74d |
| @clerk/clerk-react | 4.26.1-snapshot.cecf74d |
| @clerk/remix | 3.0.3-snapshot.cecf74d |
| @clerk/clerk-sdk-node | 4.12.10-snapshot.cecf74d |
| @clerk/shared | 0.24.1-snapshot.cecf74d |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.30.1-snapshot.cecf74d
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.4.4-snapshot.cecf74d
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.59.1-snapshot.cecf74d
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.19.6-snapshot.cecf74d
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.11-snapshot.cecf74d
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.12-snapshot.cecf74d
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.25.1-snapshot.cecf74d
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.26.1-snapshot.cecf74d
```
```sh
# @clerk/remix
npm i @clerk/remix@3.0.3-snapshot.cecf74d
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.10-snapshot.cecf74d
```
```sh
# @clerk/shared
npm i @clerk/shared@0.24.1-snapshot.cecf74d
```

**Comment by nikosdouvlis** [comment]
@OwenVey Thank you for reporting this one, forwarding this to the team ASAP

**Comment by royanger** [comment]
@OwenVey, if you import the Server Action into a Server Component and then pass it as a prop to the Client Component does that resolve the issue?

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
