### PR TITLE
refactor(clerk-sdk-node): Convert authenticateRequest params to named

### PR DESCRIPTION
**Pull request by desiprisg**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [x] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

### CODE REVIEW

**Comment by panteliselef** [comment]
Are we sure this is not a breaking change ?

**Review by SokratisVidros — APPROVED** [review]

**Review by SokratisVidros — CHANGES_REQUESTED** [review]
It is. @desiprisg Can we overload the function signature and deprecate the old one?

**Comment by panteliselef** [comment]
@SokratisVidros  Maybe it isn't tho ? Is it just internal ? 

image

**Comment by nikosdouvlis** [comment]
This is *not* a breaking change - `authenticateRequest` is not a public export and it is not the same type/function returned from the public `createAuthenticateRequest` that is actually exported.

**Review by dimkl — APPROVED** [review]

**Review by SokratisVidros — APPROVED** [review]

**Pull request merged**
