### PR TITLE
chore(repo): Format codebase with new prettier rules

### PR DESCRIPTION
**Pull request by nikosdouvlis**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [x] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

Sane formatting rules, while keeping jsx clean with the new `singleAttributePerLine` prettier config option. Any feedback is welcome :) 

### Examples
From:
```tsx
{!!browser && (
  <div className='cl-activity-prop cl-activity-browser'>{browser}</div>
)}
{!!ipAddress && (
  <div className='cl-activity-prop cl-activity-ipAddress'>
    {ipAddress}
  </div>
)}
{!!location && (
  <div className='cl-activity-prop cl-activity-location'>{location}</div>
)}
```
to:
```tsx
{!!browser && <div className='cl-activity-prop cl-activity-browser'>{browser}</div>}
{!!ipAddress && <div className='cl-activity-prop cl-activity-ipAddress'>{ipAddress}</div>}
{!!location && <div className='cl-activity-prop cl-activity-location'>{location}</div>}
```

From:
```tsx
const cb =
  typeof callbackOrOptions === 'function' ? callbackOrOptions : undefined;
const opts =
  callbackOrOptions && typeof callbackOrOptions === 'object'
   ? callbackOrOptions
    : options || {};
```
to:
```tsx
const cb = typeof callbackOrOptions === 'function' ? callbackOrOptions : undefined;
const opts = callbackOrOptions && typeof callbackOrOptions === 'object' ? callbackOrOptions : options || {};
```

### CODE REVIEW

**Comment by SokratisVidros** [comment]
@nikosdouvlis Is it expected for all JSX files with more than 1 prop to be in separate lines? I don't see this happening in the PR for all files.

**Comment by nikosdouvlis** [comment]
> @nikosdouvlis Is it expected for all JSX files with more than 1 prop to be in separate lines? I don't see this happening in the PR for all files.

Hey Sokrati - I scrolled a bit but couldn't find one, can you share an example?

**Comment by SokratisVidros** [comment]
I guess I am a bit confused. For example, do we prefer the changes as show here: https://github.com/clerkinc/javascript/pull/124/files#diff-f5889093191f9f584dc4d5ae48c435a2872335835ba0953cc7ee7c329c739fe6R11?

**Review by SokratisVidros — APPROVED** [review]
As discussed offline we decided to proceed with this prettier setup.

**Pull request merged**
