### PR TITLE
chore(repo): Check changeset against origin/main

### PR DESCRIPTION
**Pull request by dimkl**
## Description

This change will allow us to avoid always having a main branch locally and to avoid having to update it before creating a changeset.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [x] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [x] `build/tooling/chore`

### CODE REVIEW

**Comment by LekoArts** [comment]
We already do this in CI here:
https://github.com/clerkinc/javascript/blob/e613c04ef0c5dbe787362736400536b2eb47f57d/.github/workflows/quality.yml#L65

My current workflow is to just push a PR without a changeset and if the check complains you can use the bot to add a changeset (the bot is there anyways). Best of both worlds?

**Comment by dimkl** [comment]
> ❓ You would still have to have fetched the latest from remote origin however. How does this make things easier/faster/better? Maybe I am missing something.

Current steps to create a changeset from local repository:
```
# current HEAD in current-branch

# 1st approach
git fetch --all
git checkout main
git rebase origin/main 
git checkout current-branch
npm run changeset

# 2nd approach
git checkout main 
git pull origin --rebase
git checkout current-branch
npm run changeset
```

Steps after PR:
```
# current HEAD in current-branch

git fetch --all
npm run changeset
```

cc: @fragoulis

**Comment by dimkl** [comment]
> We already do this in CI here:
> 
> https://github.com/clerkinc/javascript/blob/e613c04ef0c5dbe787362736400536b2eb47f57d/.github/workflows/quality.yml#L65
> 
> My current workflow is to just push a PR without a changeset and if the check complains you can use the bot to add a changeset (the bot is there anyways). Best of both worlds?

This PR is meant to be an improvement to how we could create a changeset locally. We could avoid making a changeset locally and only create it via the bot and close this PR. Is there a consideration about why we should NOT make this change?
cc: @LekoArts

**Comment by LekoArts** [comment]
Oh, yeah, I didn't mean to say that we should close this PR. Just wanted to explain my preferred workflow. No objections for this PR if it improves your workflow.

**Review by nikosdouvlis — APPROVED** [review]

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
