### PR TITLE
fix(localizations): Make emailAddresses GE translation consistent

### PR DESCRIPTION
**Pull request by matukosan**
## Type of change

- [X] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [X] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by dimkl** [comment]
@matukosan thank you for the contribution! 🎉 🎉 
Could you please update the PR title and the commit message based like this:
```
fix(localizations): Make emailAddresses GE translation consistent
```
Clerk uses conventional commit specification for writing commit messages.

ref: https://github.com/clerkinc/javascript/blob/main/packages/localizations/docs/CONTRIBUTING.md#how-to-submit-a-pull-request

PS: i will update the docs with an example of how the commit message and the PR title should be 😅

**Review by dimkl — APPROVED** [review]

**Review by dimkl — CHANGES_REQUESTED** [review]
check the comment about the commit message

**Comment by matukosan** [comment]
> check the comment about the commit message

@dimkl thanks for the hint, changed the commit message, hope this is fine now

**Review by dimkl — APPROVED** [review]

**Comment by matukosan** [comment]
@dimkl thanks for merging 😊 can you say when this will be released?

**Comment by dimkl** [comment]
Probably this Tuesday. I add a comment in this PR when it's released.

**Pull request merged**
