### PR TITLE
fix(clerk-js): Persist history state when removing a clerk query param

### PR DESCRIPTION
**Pull request by panteliselef**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

### CODE REVIEW

**Comment by desiprisg** [comment]
Did this actually cause any problems like we thought it would?

**Review by nikosdouvlis — APPROVED** [review]
This makes sense. Can we please write more details in the PR's description for future reference?

Also, was this raised by a customer? If it yes, then let's also add a changeset.

**Comment by desiprisg** [comment]
No, it was raised by me as this theoretically will break any framework's custom routing logic when trying to navigate back to that state.

**Comment by nikosdouvlis** [comment]
> No, it was raised by me as this theoretically will break any framework's custom routing logic when trying to navigate back to that state.

That makes sense. @panteliselef let's merge this one, it's good to go

**Review by desiprisg — APPROVED** [review]

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
