### PR TITLE
fix(nextjs, shared): Restores reverted commits and fixes issue with shared in nextjs

### PR DESCRIPTION
**Pull request by dimkl**
## Description
**Review it per commit**

After restoring the reverted commits of https://github.com/clerkinc/javascript/pull/1806 , i found that the error was raised because there was some CSR only rendering files in `@clerk/shared` that did not have the `use client` directory set.
The culprits were:
- `packages/shared/src/hooks/contexts.tsx`
- `packages/shared/src/hooks/createContextAndHook.ts`

I tested the fix in the local `playground/app-router` and it seems that there is no error thrown.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [x] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [x] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by LekoArts** [comment]
Since we've seen issues with this PR I think this round we should be more conservative and test more extensively. Basically, we'll need to check our usages of `useX` hooks and see those files have the `use client` directive.

We probably should do two things for sure:
- Test out a snapshot of this PR in apps other than `playground/app-router`. I'm not confident that this is a complete site that could show all errors
- Try using https://github.com/roginfarrer/eslint-plugin-react-server-components and see if it shows anything helpful (I haven't used it yet, only read its code)

**Comment by dimkl** [comment]
> Does it make sense to group all client related stuff with a "client-boundary" folder/file like we do for nextjs ?

Let's open a discussion in team-js channel and see how it goes. I think it makes sense.

**Comment by nikosdouvlis** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @nikosdouvlis - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.30.2-snapshot.bffe9d9 |
| @clerk/chrome-extension | 0.4.5-snapshot.bffe9d9 |
| @clerk/clerk-js | 4.60.0-snapshot.bffe9d9 |
| @clerk/clerk-expo | 0.19.7-snapshot.bffe9d9 |
| @clerk/fastify | 0.6.12-snapshot.bffe9d9 |
| gatsby-plugin-clerk | 4.4.13-snapshot.bffe9d9 |
| @clerk/localizations | 1.26.3-snapshot.bffe9d9 |
| @clerk/nextjs | 4.25.2-snapshot.bffe9d9 |
| @clerk/clerk-react | 4.26.2-snapshot.bffe9d9 |
| @clerk/remix | 3.0.4-snapshot.bffe9d9 |
| @clerk/clerk-sdk-node | 4.12.11-snapshot.bffe9d9 |
| @clerk/shared | 0.24.2-snapshot.bffe9d9 |
| @clerk/themes | 1.7.7-snapshot.bffe9d9 |
| @clerk/types | 3.54.0-snapshot.bffe9d9 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.30.2-snapshot.bffe9d9
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.4.5-snapshot.bffe9d9
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.60.0-snapshot.bffe9d9
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.19.7-snapshot.bffe9d9
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.12-snapshot.bffe9d9
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.13-snapshot.bffe9d9
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.26.3-snapshot.bffe9d9
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.25.2-snapshot.bffe9d9
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.26.2-snapshot.bffe9d9
```
```sh
# @clerk/remix
npm i @clerk/remix@3.0.4-snapshot.bffe9d9
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.11-snapshot.bffe9d9
```
```sh
# @clerk/shared
npm i @clerk/shared@0.24.2-snapshot.bffe9d9
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.7-snapshot.bffe9d9
```
```sh
# @clerk/types
npm i @clerk/types@3.54.0-snapshot.bffe9d9
```

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
