### PR TITLE
fix(remix): Ensure interstitial is triggered on route transitions

### PR DESCRIPTION
**Pull request by BRKalow**
## Description

When fetching route data on a client-side transition, it is possible that the interstitial gets triggered. This presents an issue in a browser context because any script tags injected via `.innerHTML =` are not executed. To ensure that the interstitial is properly triggered, we add a call to `window.location.reload()` in this scenario.

It's worth noting that we ideally should not be triggering an interstitial for a client-side transition, but in the case it does happen we need to make sure it functions correctly.

fixes JS-706

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [x] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by BRKalow** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @BRKalow - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.29.1-snapshot.d9f7293 |
| @clerk/chrome-extension | 0.4.0-snapshot.d9f7293 |
| @clerk/clerk-js | 4.58.0-snapshot.d9f7293 |
| @clerk/clerk-expo | 0.19.2-snapshot.d9f7293 |
| @clerk/fastify | 0.6.7-snapshot.d9f7293 |
| gatsby-plugin-clerk | 4.4.8-snapshot.d9f7293 |
| @clerk/localizations | 1.26.0-snapshot.d9f7293 |
| @clerk/nextjs | 4.24.0-snapshot.d9f7293 |
| @clerk/clerk-react | 4.25.0-snapshot.d9f7293 |
| @clerk/remix | 2.10.3-snapshot.d9f7293 |
| @clerk/clerk-sdk-node | 4.12.6-snapshot.d9f7293 |
| @clerk/shared | 0.22.1-snapshot.d9f7293 |
| @clerk/types | 3.52.0-snapshot.d9f7293 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.29.1-snapshot.d9f7293
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.4.0-snapshot.d9f7293
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.58.0-snapshot.d9f7293
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.19.2-snapshot.d9f7293
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.7-snapshot.d9f7293
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.8-snapshot.d9f7293
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.26.0-snapshot.d9f7293
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.24.0-snapshot.d9f7293
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.25.0-snapshot.d9f7293
```
```sh
# @clerk/remix
npm i @clerk/remix@2.10.3-snapshot.d9f7293
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.6-snapshot.d9f7293
```
```sh
# @clerk/shared
npm i @clerk/shared@0.22.1-snapshot.d9f7293
```
```sh
# @clerk/types
npm i @clerk/types@3.52.0-snapshot.d9f7293
```

**Review by panteliselef — APPROVED** [review]
I've tested this with `https://clerk-satellite-remix.dev/` and the bug is fixed 
🎉

**Review by desiprisg — APPROVED** [review]

**Review by anagstef — APPROVED** [review]

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
