### PR TITLE
fix(clerk-js): Fix ApplyVariants and other tsc related errors

### PR DESCRIPTION
**Pull request by desiprisg**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

This PR fixes some tsc errors in the primitives.
Decided to rename `theme.ts` to `emotion.d.ts` in order to not have to explicitely include it in the `tsconfig.json`.

### CODE REVIEW

**Comment by desiprisg** [comment]
Turns out that this fixes another issue for now, and not the intended one.

**Comment by SokratisVidros** [comment]
@desiprisg I am a bit confused with this PR. Why do we need to remove React imports? Can you also elaborate on the original error?

**Comment by desiprisg** [comment]
Yes. The tracking of the type resolves typescript errors in the primitive components. The react imports are flagged as unused and appear as errors during the build as well.

**Comment by desiprisg** [comment]
The original error has also been resolved, along with some other cleanups.

**Review by nikosdouvlis — APPROVED** [review]
Changing the applyVariants interface to a type seems to have resolved the issue, nicely done.
Merging this one, let's also fix the last remaining few TS errors now on a separate PR

**Pull request merged**
