### PR TITLE
adds `sessionClaims` to auth object on request.

### LINKED ISSUE #826: Include sessionClaims when injecting auth into request.
Specifically, I'd like access to`sessionClaims.orgs`

## Package

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

## Description

Is there a reason why we don't include the session claims by default and only include the actor? 
See: https://github.com/clerkinc/javascript/blob/main/packages/remix/src/ssr/utils.ts#L20

### PR DESCRIPTION
**Pull request by nicksrandall**
Fixes #826

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

### CODE REVIEW

**Comment by nicksrandall** [comment]
@SokratisVidros does this look ok?

**Comment by dimkl** [comment]
Hello @nicksrandall let me take a look and come back to you. Until then could you please update the commit message based on : https://github.com/clerkinc/javascript/blob/main/docs/MONOREPO.md#a-note-on-commit-messages

**Comment by nicksrandall** [comment]
@dimkl I made this PR with the GitHub UI so I don't know how to change the commit message. Perhaps you can squash & merge this PR and set the proper commit message then?

**Comment by dimkl** [comment]
Hello @nicksrandall 👋 . Thank you for opening this PR. I made a few more changes. Closing this PR in favor of https://github.com/clerkinc/javascript/pull/843

**Pull request closed without merging**
