### PR TITLE
chore(clerk-js): Introduce GlobalAccessor utility for accessing browser globals

### PR DESCRIPTION
**Pull request by anagstef**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
@anagstef can you please add a description explaining the reasoning behind this change? 
Although I like the idea of having a utility to proxy all global access through, does this fail automatically during build/test time for clerk-expo?

**Comment by SokratisVidros** [comment]
This is a great suggestion. I was thinking about it while working at Expo. It will help us ensure that accessing global objects in non-browser envs doesn't break catastrophically.

**Comment by SokratisVidros** [comment]
@anagstef Are you planning to replace all global occurrences, also the ones in ClerkJS `ui` folder even though they are not used in expo?

**Comment by anagstef** [comment]
@nikosdouvlis No, we cannot detect the environment this is running on, so this utility fails only on runtime.

> This is a great suggestion. I was thinking about it while working at Expo. It will help us ensure that accessing global objects in non-browser envs doesn't break catastrophically.

@SokratisVidros This is actually the reason I tried to gather all the global objects in a place. I've also enabled an eslint rule to error when a global is used directly, outside of this utility.

> @anagstef Are you planning to replace all global occurrences, also the ones in ClerkJS `ui` folder even though they are not used in expo?

Yes, I'll try to gather all the occurrences in one place.

**Comment by clerk-cookie** [comment]
This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by clerk-cookie** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
