### PR TITLE
fix(clerk-js,localizations,types): Fix typo in spelling of connection

### PR DESCRIPTION
**Pull request by yourtallness**
## Type of change

- [X] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [X] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [X] `@clerk/types`
- [ ] `@clerk/themes`
- [X] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [X] `npm test` runs as expected.
- [X] `npm run build` runs as expected.

Fix small typo.

@nikosdouvlis are there any backward compatibility considerations?

### CODE REVIEW

**Review by nikosdouvlis — APPROVED** [review]
🧹

**Comment by anagstef** [comment]
Isn't this a breaking change for people that have their own localization file?

**Comment by yourtallness** [comment]
> Isn't this a breaking change for people that have their own localization file?

That's why I'm asking @nikosdouvlis if we need to do this in a backwards compatible way.

**Review by SokratisVidros — COMMENTED** [review]
It is a breaking change but we can't leave the typo as is. We should use the new and the old key at the same time until V5.

That is, we also need to add a reminder to ClerkV5 project to remove the hack.

**Review by SokratisVidros — APPROVED** [review]

**Review by nikosdouvlis — APPROVED** [review]

**Pull request merged**
