### PR TITLE
fix(clerk-js): Enforce LTR direction in code inputs

### PR DESCRIPTION
**Pull request by desiprisg**
## Description

Before:
Screenshot 2023-10-12 at 15 03 03

After:
Screenshot 2023-10-12 at 15 02 29

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Review by dimkl — APPROVED** [review]

**Comment by dimkl** [comment]
@desiprisg Could you add a screenshot with before/after the fix?

**Comment by desiprisg** [comment]
> @desiprisg Could you add a screenshot with before/after the fix?

done

**Review by anagstef — APPROVED** [review]
Great job! 

Should we also fix this padding here?

Screenshot 2023-10-12 at 15 08 39

**Review by panteliselef — APPROVED** [review]

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
