### PR TITLE
feat(localizations): Apply deprecation warnings for localizations

### PR DESCRIPTION
**Pull request by dimkl**
## Description

Show deprecation warning for `deDe` locale.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [x] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [x] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by dimkl** [comment]
Adding `@clerk/shared` in `@clerk/localizations` increases the bundle size by 5KB, that's why the Bundlewatch check fail. We need to make @clerk/share tree-shakeable before merging this PR, or we could choose one of the above solutions since the dependency of the `@clerk/shared` is temporary and will be removed in the next major version.

- temporary copy paste code of `deprecated()` helper inside `localizations` package
- increase the Bundlewatch limit from 75 KB to 80 KB until the next major version

**Comment by nikosdouvlis** [comment]
@dimkl I don't think it's worth spending more time on this - let's add a `@deprecated` comment and close this one.

**Comment by dimkl** [comment]
Closing this, since this change will be included in Changelog and the Release notes. We will proceed without adding a deprecation warning for the `@clerk/localizations` as @nikosdouvlis suggested in [his comment](https://github.com/clerkinc/javascript/pull/1790#issuecomment-1738700695)

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
