### PR TITLE
feat(clerk-js): Add white border to QR code svg

### PR DESCRIPTION
**Pull request by desiprisg**
Add a white border of 10px to the QR code svg so that it is scannable when the background is dark

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

Example with dark background: 
Screenshot 2022-12-01 at 19 35 02

### CODE REVIEW

**Review by anagstef — APPROVED** [review]
💯

**Review by nikosdouvlis — APPROVED** [review]
Does the svg have an appearance key so it can be customised by the users?

**Comment by desiprisg** [comment]
It does not. We can add a key on the container so they can target the svg.

**Comment by nikosdouvlis** [comment]
> It does not. We can add a key on the container so they can target the svg.

Lets go for it!

**Pull request merged**
