### PR TITLE
feat(localizations): Add uk-UA localization

### PR DESCRIPTION
**Pull request by demptd13**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [x] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
@demptd13 Many thanks for your contribution, this looks good :) 

Merging once the tests pass so we can release this today.

**Review by dimkl — APPROVED** [review]

**Comment by demptd13** [comment]
Hello, when you have the opportunity to add this changes to patch?

**Comment by dimkl** [comment]
hello @demptd13, the changes were deployed today in version `@clerk/localizations@1.25.0`.

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
