### PR TITLE
[WIP] Use CLERK_TRUST_HOST by default - PART 2

### PR DESCRIPTION
**Pull request by dimkl**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

### CODE REVIEW

**Comment by clerk-cookie** [comment]
Hey @dimkl - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.25.1 |
| @clerk/chrome-extension | 0.3.23 |
| @clerk/clerk-js | 4.54.0 |
| eslint-config-custom | 0.3.0 |
| @clerk/clerk-expo | 0.18.14 |
| @clerk/fastify | 0.6.1 |
| gatsby-plugin-clerk | 4.4.1 |
| @clerk/localizations | 1.23.1 |
| @clerk/nextjs | 4.23.0-snapshot.918ce9d |
| @clerk/clerk-react | 4.23.0 |
| @clerk/remix | 2.8.1 |
| @clerk/clerk-sdk-node | 4.11.1 |
| @clerk/shared | 0.20.0 |
| @clerk/themes | 1.7.5 |
| @clerk/types | 3.48.0 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.25.1
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.3.23
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.54.0
```
```sh
# eslint-config-custom
npm i eslint-config-custom@0.3.0
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.18.14
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.1
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.1
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.23.1
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.23.0-snapshot.918ce9d
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.23.0
```
```sh
# @clerk/remix
npm i @clerk/remix@2.8.1
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.11.1
```
```sh
# @clerk/shared
npm i @clerk/shared@0.20.0
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.5
```
```sh
# @clerk/types
npm i @clerk/types@3.48.0
```

**Comment by clerk-cookie** [comment]
Hey @dimkl - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.26.0-snapshot.5ce76ec |
| @clerk/chrome-extension | 0.3.23 |
| @clerk/clerk-js | 4.54.0 |
| eslint-config-custom | 0.3.0 |
| @clerk/clerk-expo | 0.18.14 |
| @clerk/fastify | 0.6.2-snapshot.5ce76ec |
| gatsby-plugin-clerk | 4.4.2-snapshot.5ce76ec |
| @clerk/localizations | 1.23.1 |
| @clerk/nextjs | 4.23.0-snapshot.5ce76ec |
| @clerk/clerk-react | 4.23.0 |
| @clerk/remix | 2.9.0-snapshot.5ce76ec |
| @clerk/clerk-sdk-node | 4.12.0-snapshot.5ce76ec |
| @clerk/shared | 0.20.0 |
| @clerk/themes | 1.7.5 |
| @clerk/types | 3.48.0 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.26.0-snapshot.5ce76ec
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.3.23
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.54.0
```
```sh
# eslint-config-custom
npm i eslint-config-custom@0.3.0
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.18.14
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.2-snapshot.5ce76ec
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.2-snapshot.5ce76ec
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.23.1
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.23.0-snapshot.5ce76ec
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.23.0
```
```sh
# @clerk/remix
npm i @clerk/remix@2.9.0-snapshot.5ce76ec
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.0-snapshot.5ce76ec
```
```sh
# @clerk/shared
npm i @clerk/shared@0.20.0
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.5
```
```sh
# @clerk/types
npm i @clerk/types@3.48.0
```

**Comment by dimkl** [comment]
Adding these changes to the base PR and closing this.

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
