### PR TITLE
ci(repo): Speed up CI via caching

### PR DESCRIPTION
**Pull request by tmilewski**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [x] other: CI optimizations

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [x] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

Speeds up the CI process through the caching of `node_modules` and Turborepo output.

### CODE REVIEW

**Comment by nikosdouvlis** [comment]
Hello @tmilewski - everything here makes sense many, thanks for another contribution! That being said, I'd like to wait a few days before merging this one for a couple of reasons.

Even though improving build time is planned (potentially for next week), there is a work-in-progress PR that needs to be merged first: https://github.com/clerkinc/javascript/pull/1072. This is almost ready to go, we'll make a few minor adjustments so we can merge before Monday hopefully. 

A second, more important reason, is that we've still investigating a few issues we had with the Turborepo cache *not being invalidated* correctly. This is extremely risky for our case as our packages rely on other internal packages - if the cache is not invalidated when a change happens (false negative), it's highly likely for a package to be released with a bumped version but old build artifacts in its `dist` directory.

Hope that makes sense.

PS: I think you've somehow managed to access our internal tech-debt roadmap :) I'd be happy to chat about future improvements you have in mind

**Comment by tmilewski** [comment]
@nikosdouvlis That's totally cool, and thank you for taking a look! I might keep playing with this PR (in draft) simply as a way to test out the false negative issues.

Do those PRs/commits, where you were having invalidation issues, exist somewhere that I can take a look? My gut says the issue is somewhere between the cache folder location (normally in `node_modules/.cache/turbo`), GitHub cache keys, and the Turborepo `inputs` config.

Happy to chat whenever! 👍

**Comment by nikosdouvlis** [comment]
Hey @tmilewski !
I'm going to close this one as we've made a pretty big revamp to our CICD process. We'll monitor how things go for the next few days, and I'll post an update then :)

**Comment by nikosdouvlis** [comment]
Hey @tmilewski !
I'm going to close this one as we've made a pretty big revamp to our CICD process. We'll monitor how things go for the next few days, and I'll post an update then :)

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
