### PR TITLE
Remove deprecated fields from Sign In, Sing Up, Display Config resources & types

### PR DESCRIPTION
**Pull request by chanioxaris**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [x] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [x] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

We have recently deprecated some fields from the sign, sign up and display config responses as they were part of an older API schema. This commit removes them from the types as well, as it's no longer used to keep them clean.

Display Config
- backend_host

Sign In
- allowed_identifier_types
- allowed_factor_one_strategies
- factor_one_verification
- factor_two_verification

Sign Up
- identification_requirements
- email_address_verification
- phone_number_verification
- external_account_strategy
- external_account_verification

### CODE REVIEW

**Review by nikosdouvlis — APPROVED** [review]
Just to confirm - all these are already removed from FAPI right? So no breaking changes here.

**Comment by panteliselef** [comment]
Isn't a move like this very much a breaking change ? Why couldn't we wait for v5 ?

**Comment by chanioxaris** [comment]
> Just to confirm - all these are already removed from FAPI right?

Yes these fields are no longer returned either from FAPI or BAPI

**Review by anagstef — APPROVED** [review]
✂️ ✂️ ✂️

**Comment by nikosdouvlis** [comment]
> Isn't a move like this very much a breaking change ? Why couldn't we wait for v5 ?

FAPI is no longer returning these anyway, so there's no need to wait for v5.

**Pull request merged**
