### PR TITLE
chore(clerk-react): Update docs about process.env

### PR DESCRIPTION
**Pull request by dimkl**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

Drop REACT_APP_CLERK_FRONTEND_API environment variable usage example from docs.

### CODE REVIEW

**Comment by dimkl** [comment]
Should i also replace frontendApi with publishableKey?

**Comment by anagstef** [comment]
> Should i also replace frontendApi with publishableKey?

Sure! :)

**Review by anagstef — APPROVED** [review]

**Review by nikosdouvlis — APPROVED** [review]

**Review by nikosdouvlis — APPROVED** [review]
Thanks Dimitri

**Comment by dimkl** [comment]
After discussing it with @nikosdouvlis we have agreed to proceed with keeping the usage of `process.env` in our readme example and update the example to use `publishableKey` instead of `frontendApi`.
That decision was taken because `process.env` is used in [clerk-react](https://clerk.dev/docs/quickstarts/get-started-with-create-react-app#adding-clerk-provider) official docs example and in the [create-react-app](https://create-react-app.dev/docs/adding-custom-environment-variables/) official docs.

cc: @SokratisVidros

**Pull request merged**
