### PR TITLE
fix(sdk-node): Fall back to secret key if no JWT key is set, per defaults behavior

### PR DESCRIPTION
**Pull request by jlengstorf**
## Description

when verifying a session with the Node SDK, a JWT key is required. if no custom JWT key is set, Clerk falls back to the secret key. this change makes the SDK implement the stated default behavior

Screenshot 2023-10-04 at 14 54 47

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi Jason 👋 Long time no see 😊 

I've asked internally if this is the right change and it turns out that the default behavior described there is already happening:

https://github.com/clerkinc/javascript/blob/7636abc105c9436bc6ada93df3fa7da2b53ca340/packages/backend/src/tokens/verify.ts#L46-L60

The `SECRET_KEY` and `API_KEY` are related to authenticate with Clerk's backend API. `jwtKey` is for validating the session token JWT.
In that above flow the two keys are used on https://clerk.com/docs/reference/backend-api/tag/JWKS#operation/GetJWKS to get the jwtKey (since it doesn't exist).

Hope that makes sense! If something is not working as intended and that was the reason for the PR, please let us know. Thanks!

**Comment by jlengstorf** [comment]
hey @LekoArts! yes, I had to make this change to get the code to work. without that env var, every session was reported as invalid

so I'm not sure where things are disconnecting, but something is misbehaving along the lines

**Comment by LekoArts** [comment]
@jlengstorf Ok, gotcha. Do you have an example/minimal reproduction at hand where I could see this behavior?

Was this part of this repo? https://github.com/learnwithjason/4d1a-productivity-tracker
I see that you changed implementation a bit

**Comment by jlengstorf** [comment]
@LekoArts sorry I missed this reply. yeah, your team did a pretty extensive rewrite of how I was implementing this 😅

**Pull request closed without merging**
