### PR TITLE
chore(repo): Bump node version matrix for Github actions

### PR DESCRIPTION
**Pull request by SokratisVidros**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

### CODE REVIEW

**Review by nikosdouvlis — APPROVED** [review]

**Review by dimkl — APPROVED** [review]

**Comment by nikosdouvlis** [comment]
```
@clerk/shared:test:     Expected: "11:15 PM"
@clerk/shared:test:     Received: "11:15 PM"
```

The date issue is back again :)
I'll try to tackle this today as the last node version that works consistently is `18.12.1`

**Comment by nikosdouvlis** [comment]
This failed initially because of a different white space character produced by specific node versions. This broke in node 18.12.2 and is now solved in >18.15 and >19.8

**Comment by dimkl** [comment]
Screenshot 2023-03-16 at 10 53 56
Why does `build` checks node versions of this PR are still the ones ?

**Comment by nikosdouvlis** [comment]
> Screenshot 2023-03-16 at 10 53 56
> 
> Why does `build` checks node versions of this PR are still the ones ?

Not related to the PR itself, we just need to update the github status checks for the new job names. WIll do that shortly.

**Pull request merged**
