### PR TITLE
fix(shared): Improve expo compat

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

The goal of this PR is improve the compat of our `@clerk/shared` package with Expo. Unfortunately Expo has limited support with the `exports` map (https://reactnative.dev/blog/2023/06/21/package-exports-support) and in addition, it doesn't support `.mjs` files by default (see https://github.com/expo/expo/issues/23180) 🤷 
We don't want to give up the proper `exports` syntax as a workaround for now we can generate folders with `package.json` files before publishing and add them to the `files` key.

For this the `@clerk/shared` package now has a `postbuild` script to generate this. The information for it is hardcoded as it's easier than trying to write a "smart" script to handle all the cases. This also means that if we add a new subpath, we should add the name to the `subpaths.mjs` file.

The result is this output: https://unpkg.com/browse/@clerk/shared@1.0.1-snapshot.vceb8c8a/

Now when Expo tries to reach `@clerk/shared/deprecated` it'll use the folder.
I also removed the "type": "module" as modern solutions should use exports map anyways and Expo won't try to use a file that uses .mjs

Fixes SDK-857

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

### CODE REVIEW

**Comment by LekoArts** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @LekoArts - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 0.4.11-snapshot.v8d8b68e |
| @clerk/clerk-js | 4.64.0-snapshot.v8d8b68e |
| @clerk/clerk-expo | 0.19.13-snapshot.v8d8b68e |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.4.11-snapshot.v8d8b68e --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.64.0-snapshot.v8d8b68e --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.13-snapshot.v8d8b68e --save-exact
```

**Comment by LekoArts** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @LekoArts - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.31.4-snapshot.vdd066c4 |
| @clerk/chrome-extension | 0.4.11-snapshot.vdd066c4 |
| @clerk/clerk-js | 4.64.0-snapshot.vdd066c4 |
| @clerk/clerk-expo | 0.19.13-snapshot.vdd066c4 |
| @clerk/fastify | 0.6.18-snapshot.vdd066c4 |
| gatsby-plugin-clerk | 4.4.19-snapshot.vdd066c4 |
| @clerk/nextjs | 4.25.8-snapshot.vdd066c4 |
| @clerk/clerk-react | 4.27.1-snapshot.vdd066c4 |
| @clerk/remix | 3.1.1-snapshot.vdd066c4 |
| @clerk/clerk-sdk-node | 4.12.17-snapshot.vdd066c4 |
| @clerk/shared | 1.0.1-snapshot.vdd066c4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.31.4-snapshot.vdd066c4 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.4.11-snapshot.vdd066c4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.64.0-snapshot.vdd066c4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.13-snapshot.vdd066c4 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.18-snapshot.vdd066c4 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.19-snapshot.vdd066c4 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.25.8-snapshot.vdd066c4 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.27.1-snapshot.vdd066c4 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.1-snapshot.vdd066c4 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.12.17-snapshot.vdd066c4 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@1.0.1-snapshot.vdd066c4 --save-exact
```

**Comment by LekoArts** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @LekoArts - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.31.4-snapshot.vfaf78f6 |
| @clerk/chrome-extension | 0.4.11-snapshot.vfaf78f6 |
| @clerk/clerk-js | 4.64.0-snapshot.vfaf78f6 |
| @clerk/clerk-expo | 0.19.13-snapshot.vfaf78f6 |
| @clerk/fastify | 0.6.18-snapshot.vfaf78f6 |
| gatsby-plugin-clerk | 4.4.19-snapshot.vfaf78f6 |
| @clerk/nextjs | 4.25.8-snapshot.vfaf78f6 |
| @clerk/clerk-react | 4.27.1-snapshot.vfaf78f6 |
| @clerk/remix | 3.1.1-snapshot.vfaf78f6 |
| @clerk/clerk-sdk-node | 4.12.17-snapshot.vfaf78f6 |
| @clerk/shared | 1.0.1-snapshot.vfaf78f6 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.31.4-snapshot.vfaf78f6 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.4.11-snapshot.vfaf78f6 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.64.0-snapshot.vfaf78f6 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.13-snapshot.vfaf78f6 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.18-snapshot.vfaf78f6 --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.19-snapshot.vfaf78f6 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.25.8-snapshot.vfaf78f6 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.27.1-snapshot.vfaf78f6 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.1-snapshot.vfaf78f6 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.12.17-snapshot.vfaf78f6 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@1.0.1-snapshot.vfaf78f6 --save-exact
```

**Comment by LekoArts** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @LekoArts - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.31.4-snapshot.vceb8c8a |
| @clerk/chrome-extension | 0.4.11-snapshot.vceb8c8a |
| @clerk/clerk-js | 4.64.0-snapshot.vceb8c8a |
| @clerk/clerk-expo | 0.19.13-snapshot.vceb8c8a |
| @clerk/fastify | 0.6.18-snapshot.vceb8c8a |
| gatsby-plugin-clerk | 4.4.19-snapshot.vceb8c8a |
| @clerk/nextjs | 4.25.8-snapshot.vceb8c8a |
| @clerk/clerk-react | 4.27.1-snapshot.vceb8c8a |
| @clerk/remix | 3.1.1-snapshot.vceb8c8a |
| @clerk/clerk-sdk-node | 4.12.17-snapshot.vceb8c8a |
| @clerk/shared | 1.0.1-snapshot.vceb8c8a |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/backend`
```sh
npm i @clerk/backend@0.31.4-snapshot.vceb8c8a --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@0.4.11-snapshot.vceb8c8a --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@4.64.0-snapshot.vceb8c8a --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@0.19.13-snapshot.vceb8c8a --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@0.6.18-snapshot.vceb8c8a --save-exact
```
`gatsby-plugin-clerk`
```sh
npm i gatsby-plugin-clerk@4.4.19-snapshot.vceb8c8a --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@4.25.8-snapshot.vceb8c8a --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@4.27.1-snapshot.vceb8c8a --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@3.1.1-snapshot.vceb8c8a --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@4.12.17-snapshot.vceb8c8a --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@1.0.1-snapshot.vceb8c8a --save-exact
```

**Review by nikosdouvlis — APPROVED** [review]

**Pull request merged**
