### PR TITLE
feat(backend): Expose organization createdBy

### PR DESCRIPTION
**Pull request by gkats**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [x] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [x] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

Added the createdBy property in the Organization resource.

### CODE REVIEW

**Review by anagstef — APPROVED** [review]
💯

**Review by dimkl — COMMENTED** [review]
❓ Shouldn't `created_by` be added to `OrganizationResource` of `@clerk/types` ?

**Comment by gkats** [comment]
> Shouldn't created_by be added to OrganizationResource of @clerk/types ?

I guess you're right, these types are used in both backend and frontend sdks. I'll create a follow-up PR.

**Comment by gkats** [comment]
@dimkl Checked again and it looks like the `OrganizationResource` interface is used only for clerkJS and React. The `createdBy` property is not available there.

It's used only by our backend API.

Do you still think I should update the types package? Am I missing something?

**Comment by dimkl** [comment]
> @dimkl Checked again and it looks like the `OrganizationResource` interface is used only for clerkJS and React. The `createdBy` property is not available there.
> 
> It's used only by our backend API.
> 
> Do you still think I should update the types package? Am I missing something?

You are correct we don't need to add it in `types` since it's only used in BAPI response.

**Pull request merged**
