### PR TITLE
fix(clerk-js): Update redirection FAPI Accounts to include accountstage

### PR DESCRIPTION
**Pull request by msakbar**
## Type of change

- [X] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [X] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

Just including accountstage so that staging AP can also get properly redirected. See Linear: https://linear.app/clerk/issue/JS-506/accountstagedev-is-not-accounted-for-in-the-redirections

### CODE REVIEW

**Review by dimkl — APPROVED** [review]
I have changed the regex and added a test for the staging accounts case.
Thank you for opening this PR and sorry for editing your PR 😅

**Review by nikosdouvlis — APPROVED** [review]
That makes sense, thanks @msakbar :)
@dimkl there are 2-3 places where we have similar logic, let's discuss ideas on how to make this a little more maintainable. Moving everything to share might be enough?

**Comment by dimkl** [comment]
> That makes sense, thanks @msakbar :) @dimkl there are 2-3 places where we have similar logic, let's discuss ideas on how to make this a little more maintainable. Moving everything to share might be enough?

@nikosdouvlis I will add it as part of a `Revamp shared package` ticket, to include this as helper method.

**Comment by msakbar** [comment]
> I have changed the regex and added a test for the staging accounts case. Thank you for opening this PR and sorry for editing your PR 😅

not at all - thank you so much for helping out, i genuinely just wanted to make it 0 effort for you to jump on this.

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
