### PR TITLE
🎉 New <OrganizationList /> component

### PR DESCRIPTION
**Pull request by panteliselef**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [x] `@clerk/remix`
- [x] `@clerk/types`
- [ ] `@clerk/themes`
- [x] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [x] `@clerk/chrome-extension`
- [x] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

# <OrganizationList />
## Our new react Component 

[Visit here to see it ](https://b2b-saas-starter.clerkpreview.com/create-organization)

It is build on top of our updated `useOrganizationList` hook and provides the UI in order for an active user to 
- see join organizations
- pending invitations
- suggestions to join organizations

The user also has the ability to create an organization within this component.
The user can "Skip and continue" to another flow.

### Usage
```tsx
<OrganizationList
  afterCreateOrganizationUrl="/org/:id"
  afterSkipUrl="/"
  afterSelectOrganizationUrl="/org/:id"
/>

```

```tsx
<OrganizationList
  createOrganizationMode='navigation'
  createOrganizationUrl='/create-org'
  afterSkipUrl="/"
  afterSelectOrganizationUrl="/org/:id"
  appearance={{...}}
/>

```

### Screenshots
image
image

Tests coming in a following PR

### CODE REVIEW

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.28.0-snapshot.08bec15 |
| @clerk/chrome-extension | 0.3.27-snapshot.08bec15 |
| @clerk/clerk-js | 4.56.0-snapshot.08bec15 |
| eslint-config-custom | 0.3.0 |
| @clerk/clerk-expo | 0.18.18-snapshot.08bec15 |
| @clerk/fastify | 0.6.4-snapshot.08bec15 |
| gatsby-plugin-clerk | 4.4.5-snapshot.08bec15 |
| @clerk/localizations | 1.25.0-snapshot.08bec15 |
| @clerk/nextjs | 4.23.3-snapshot.08bec15 |
| @clerk/clerk-react | 4.24.0-snapshot.08bec15 |
| @clerk/remix | 2.10.0-snapshot.08bec15 |
| @clerk/clerk-sdk-node | 4.12.3-snapshot.08bec15 |
| @clerk/shared | 0.22.0-snapshot.08bec15 |
| @clerk/themes | 1.7.5 |
| @clerk/types | 3.50.0-snapshot.08bec15 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.28.0-snapshot.08bec15
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.3.27-snapshot.08bec15
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.56.0-snapshot.08bec15
```
```sh
# eslint-config-custom
npm i eslint-config-custom@0.3.0
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.18.18-snapshot.08bec15
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.4-snapshot.08bec15
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.5-snapshot.08bec15
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.25.0-snapshot.08bec15
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.23.3-snapshot.08bec15
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.24.0-snapshot.08bec15
```
```sh
# @clerk/remix
npm i @clerk/remix@2.10.0-snapshot.08bec15
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.3-snapshot.08bec15
```
```sh
# @clerk/shared
npm i @clerk/shared@0.22.0-snapshot.08bec15
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.5
```
```sh
# @clerk/types
npm i @clerk/types@3.50.0-snapshot.08bec15
```

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.28.0-snapshot.6a4df90 |
| @clerk/chrome-extension | 0.3.27-snapshot.6a4df90 |
| @clerk/clerk-js | 4.56.0-snapshot.6a4df90 |
| eslint-config-custom | 0.3.0 |
| @clerk/clerk-expo | 0.18.18-snapshot.6a4df90 |
| @clerk/fastify | 0.6.4-snapshot.6a4df90 |
| gatsby-plugin-clerk | 4.4.5-snapshot.6a4df90 |
| @clerk/localizations | 1.25.0-snapshot.6a4df90 |
| @clerk/nextjs | 4.23.3-snapshot.6a4df90 |
| @clerk/clerk-react | 4.24.0-snapshot.6a4df90 |
| @clerk/remix | 2.10.0-snapshot.6a4df90 |
| @clerk/clerk-sdk-node | 4.12.3-snapshot.6a4df90 |
| @clerk/shared | 0.22.0-snapshot.6a4df90 |
| @clerk/themes | 1.7.5 |
| @clerk/types | 3.50.0-snapshot.6a4df90 |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.28.0-snapshot.6a4df90
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.3.27-snapshot.6a4df90
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.56.0-snapshot.6a4df90
```
```sh
# eslint-config-custom
npm i eslint-config-custom@0.3.0
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.18.18-snapshot.6a4df90
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.4-snapshot.6a4df90
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.5-snapshot.6a4df90
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.25.0-snapshot.6a4df90
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.23.3-snapshot.6a4df90
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.24.0-snapshot.6a4df90
```
```sh
# @clerk/remix
npm i @clerk/remix@2.10.0-snapshot.6a4df90
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.3-snapshot.6a4df90
```
```sh
# @clerk/shared
npm i @clerk/shared@0.22.0-snapshot.6a4df90
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.5
```
```sh
# @clerk/types
npm i @clerk/types@3.50.0-snapshot.6a4df90
```

**Comment by panteliselef** [comment]
!snapshot

**Comment by clerk-cookie** [comment]
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/backend | 0.28.0-snapshot.5a912ff |
| @clerk/chrome-extension | 0.3.27-snapshot.5a912ff |
| @clerk/clerk-js | 4.56.0-snapshot.5a912ff |
| eslint-config-custom | 0.3.0 |
| @clerk/clerk-expo | 0.18.18-snapshot.5a912ff |
| @clerk/fastify | 0.6.4-snapshot.5a912ff |
| gatsby-plugin-clerk | 4.4.5-snapshot.5a912ff |
| @clerk/localizations | 1.25.0-snapshot.5a912ff |
| @clerk/nextjs | 4.23.3-snapshot.5a912ff |
| @clerk/clerk-react | 4.24.0-snapshot.5a912ff |
| @clerk/remix | 2.10.0-snapshot.5a912ff |
| @clerk/clerk-sdk-node | 4.12.3-snapshot.5a912ff |
| @clerk/shared | 0.22.0-snapshot.5a912ff |
| @clerk/themes | 1.7.5 |
| @clerk/types | 3.50.0-snapshot.5a912ff |

Tip: use the snippet copy button below to quickly install the required packages.
```sh
# @clerk/backend
npm i @clerk/backend@0.28.0-snapshot.5a912ff
```
```sh
# @clerk/chrome-extension
npm i @clerk/chrome-extension@0.3.27-snapshot.5a912ff
```
```sh
# @clerk/clerk-js
npm i @clerk/clerk-js@4.56.0-snapshot.5a912ff
```
```sh
# eslint-config-custom
npm i eslint-config-custom@0.3.0
```
```sh
# @clerk/clerk-expo
npm i @clerk/clerk-expo@0.18.18-snapshot.5a912ff
```
```sh
# @clerk/fastify
npm i @clerk/fastify@0.6.4-snapshot.5a912ff
```
```sh
# gatsby-plugin-clerk
npm i gatsby-plugin-clerk@4.4.5-snapshot.5a912ff
```
```sh
# @clerk/localizations
npm i @clerk/localizations@1.25.0-snapshot.5a912ff
```
```sh
# @clerk/nextjs
npm i @clerk/nextjs@4.23.3-snapshot.5a912ff
```
```sh
# @clerk/clerk-react
npm i @clerk/clerk-react@4.24.0-snapshot.5a912ff
```
```sh
# @clerk/remix
npm i @clerk/remix@2.10.0-snapshot.5a912ff
```
```sh
# @clerk/clerk-sdk-node
npm i @clerk/clerk-sdk-node@4.12.3-snapshot.5a912ff
```
```sh
# @clerk/shared
npm i @clerk/shared@0.22.0-snapshot.5a912ff
```
```sh
# @clerk/themes
npm i @clerk/themes@1.7.5
```
```sh
# @clerk/types
npm i @clerk/types@3.50.0-snapshot.5a912ff
```

**Comment by panteliselef** [comment]
Closing this for now, as we are considering changes in the UI

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
