### PR TITLE
feat: Initial Solid adapter

### PR DESCRIPTION
**Pull request by OrJDev**
## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [x] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [x] **new**: `@clerk/clerk-solid`
- [x] **new**: `@clerk/utils`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

This will add an initial adapter for SolidJS, also makes it easier to build more packages for Clerk by making utils actually agnostic (`@clerk/shared` is not agnostic, its utilities have been moved to `@clerk/utils`).

Don't merge yet, ***WIP**

### CODE REVIEW

**Comment by OrJDev** [comment]
Btw husky pissed me off and didn't allow me adding solid & utils so i just removed it for now, we can add it later

**Comment by dimkl** [comment]
Hello @OrJDev . Thank you sooo much for the contribution.
Since this PR is enormous i would like to suggest if it's possible to either split it into separate PRs and group the changes to make it easier for us to review. Or make commits depict group of related changes with information about why this change should be made.
I am gonna prepare a Contributing doc in the repo that will describe how to open a PR and make a contribution. Some basics from code styling to code structures and commit / PR conventions used.
For now i would like to point that we are using conventional commit specification and the format of our commits have the following format:
```
fix | feat | chore(packages_affected, ...) : Change reasoning

More information and/or examples and reference links
```

**Comment by LLBlumire** [comment]
Are you planning on implementing a `clerk-solid-start`, similar to `clerk-nextjs`, or is this initial implementation just covering `clerk-solid` as equivalent to `cleark-react`?

**Comment by OrJDev** [comment]
> Are you planning on implementing a `clerk-solid-start`, similar to `clerk-nextjs`, or is this initial implementation just covering `clerk-solid` as equivalent to `cleark-react`?

Yes i plan to, this is just the initial so we can get the logic working in SolidJS

**Comment by OrJDev** [comment]
> Hello @OrJDev . Thank you sooo much for the contribution.
> 
> Since this PR is enormous i would like to suggest if it's possible to either split it into separate PRs and group the changes to make it easier for us to review. Or make commits depict group of related changes with information about why this change should be made.
> 
> I am gonna prepare a Contributing doc in the repo that will describe how to open a PR and make a contribution. Some basics from code styling to code structures and commit / PR conventions used.
> 
> For now i would like to point that we are using conventional commit specification and the format of our commits have the following format:
> 
> ```
> 
> fix | feat | chore(packages_affected, ...) : Change reasoning
> 
> 
> 
> More information and/or examples and reference links
> 
> ```
> 
> 
> 
> Also could you rename the package name and the folder to `solid`  (eg `packages/solid` , `@clerk/solid`) ?

Sure will do everything here, first i want to get it to to fully work

**Comment by btfranklin** [comment]
Hey, just curious what's going on with this. Is it still in progress?

**Comment by OrJDev** [comment]
> Hey, just curious what's going on with this. Is it still in progress?

There is an issue blocking me from doing this https://github.com/clerkinc/javascript/issues/1143

**Comment by clerk-cookie** [comment]
This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by clerk-cookie** [comment]
This PR was closed because it has been stalled for 10 days with no activity.

**Comment by clerk-cookie** [comment]
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
